<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => false,
'inlineEdit' => false,
'delete' => false,
'updateSelected' => false,
'addInPopup' => null,
'editInPopup' => false,
'viewInPopup' => true,
'clickSort' => false,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'contractor_id' => array( 'totalsType' => '' ),
'contractor_type' => array( 'totalsType' => '' ),
'contractor_doc_id' => array( 'totalsType' => '' ),
'contractor_doc_dv' => array( 'totalsType' => '' ),
'contractor_pwd' => array( 'totalsType' => '' ),
'contractor_image' => array( 'totalsType' => '' ),
'contractor_name' => array( 'totalsType' => '' ),
'contractor_lname' => array( 'totalsType' => '' ),
'contractor_nombresfull' => array( 'totalsType' => '' ),
'enlace_sigep' => array( 'totalsType' => '' ),
'contractor_email' => array( 'totalsType' => '' ),
'contractor_email_mincit' => array( 'totalsType' => '' ),
'contractor_address' => array( 'totalsType' => '' ),
'contractor_phone' => array( 'totalsType' => '' ),
'contractor_mobile' => array( 'totalsType' => '' ),
'contractor_city' => array( 'totalsType' => '' ),
'contractor_sup_jerarquico' => array( 'totalsType' => '' ),
'contractor_dependencia' => array( 'totalsType' => '' ),
'bank_name' => array( 'totalsType' => '' ),
'bank_cta_type' => array( 'totalsType' => '' ),
'bank_cta_number' => array( 'totalsType' => '' ),
'iva_regimen' => array( 'totalsType' => '' ),
'sys_update' => array( 'totalsType' => '' ),
'sys_user' => array( 'totalsType' => '' ),
'sys_date' => array( 'totalsType' => '' ),
'sys_level' => array( 'totalsType' => '' ),
'sys_status' => array( 'totalsType' => '' ),
'sys_last_upd' => array( 'totalsType' => '' ),
'groupid' => array( 'totalsType' => '' ),
'active' => array( 'totalsType' => '' ),
'contractor_dependientes' => array( 'totalsType' => '' ),
'contractor_medicinapre_file' => array( 'totalsType' => '' ),
'contractor_picmonetaria_file' => array( 'totalsType' => '' ),
'contractor_decljur' => array( 'totalsType' => '' ),
'contractor_eps' => array( 'totalsType' => '' ),
'contractor_fondopensiones' => array( 'totalsType' => '' ),
'contractor_cajacompensacion' => array( 'totalsType' => '' ),
'contractor_arl' => array( 'totalsType' => '' ),
'ubica_dep' => array( 'totalsType' => '' ),
'ubica_extension' => array( 'totalsType' => '' ),
'dem_genero' => array( 'totalsType' => '' ),
'dem_ocupacion' => array( 'totalsType' => '' ),
'dem_profesion' => array( 'totalsType' => '' ),
'ct_fecha_nacimiento' => array( 'totalsType' => '' ),
'ct_nacionalidad' => array( 'totalsType' => '' ),
'dem_edad' => array( 'totalsType' => '' ),
'dem_educacion' => array( 'totalsType' => '' ),
'dem_discapacidad' => array( 'totalsType' => '' ),
'emergencia' => array( 'totalsType' => '' ),
'terms_msj' => array( 'totalsType' => '' ),
'terms_acepta' => array( 'totalsType' => '' ),
'signature' => array( 'totalsType' => '' ),
'pin' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'contractor_email_mincit',
'contractor_email',
'contractor_lname',
'contractor_name',
'contractor_image',
'contractor_doc_id',
'dem_profesion',
'contractor_sup_jerarquico',
'contractor_dependencia' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'dem_profesion',
'contractor_dependencia',
'contractor_sup_jerarquico',
'terms_acepta',
'terms_msj',
'emergencia',
'dem_discapacidad',
'dem_educacion',
'dem_edad',
'ct_nacionalidad',
'ct_fecha_nacimiento',
'dem_ocupacion',
'dem_genero',
'ubica_extension',
'ubica_dep',
'contractor_arl',
'contractor_cajacompensacion',
'contractor_fondopensiones',
'contractor_eps',
'contractor_decljur',
'contractor_picmonetaria_file',
'contractor_medicinapre_file',
'contractor_dependientes',
'active',
'groupid',
'sys_last_upd',
'sys_status',
'sys_level',
'sys_date',
'sys_user',
'sys_update',
'iva_regimen',
'bank_cta_number',
'bank_cta_type',
'bank_name',
'contractor_city',
'contractor_mobile',
'contractor_phone',
'contractor_address',
'contractor_email_mincit',
'contractor_email',
'enlace_sigep',
'contractor_nombresfull',
'contractor_lname',
'contractor_name',
'contractor_pwd',
'contractor_doc_dv',
'contractor_doc_id',
'contractor_type',
'contractor_id',
'contractor_image' ),
'filterFields' => array(  ),
'inlineAddFields' => array(  ),
'inlineEditFields' => array(  ),
'fieldItems' => array( 'contractor_email_mincit' => array( 'simple_grid_field11',
'simple_grid_field14' ),
'contractor_email' => array( 'simple_grid_field10',
'simple_grid_field13' ),
'contractor_lname' => array( 'simple_grid_field7',
'simple_grid_field12' ),
'contractor_name' => array( 'simple_grid_field6',
'simple_grid_field9' ),
'contractor_image' => array( 'simple_grid_field5',
'simple_grid_field8' ),
'contractor_doc_id' => array( 'simple_grid_field2',
'simple_grid_field' ),
'dem_profesion' => array( 'grid_field',
'grid_field_label' ),
'contractor_sup_jerarquico' => array( 'grid_field1',
'grid_field_label1' ),
'contractor_dependencia' => array( 'grid_field2',
'grid_field_label2' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => true,
'add' => false,
'view' => true,
'print' => true ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'left' => array( 'logo1',
'expand_button',
'menu',
'search_panel' ),
'supertop' => array( 'collapse_button',
'breadcrumb',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'above-grid' => array( 'details_found',
'page_size',
'print_panel' ),
'below-grid' => array( 'pagination' ),
'grid' => array( 'grid_checkbox',
'grid_edit',
'grid_view',
'simple_grid_field',
'simple_grid_field2',
'grid_field_label',
'grid_field',
'simple_grid_field13',
'simple_grid_field10',
'simple_grid_field14',
'simple_grid_field11',
'simple_grid_field8',
'simple_grid_field5',
'grid_field_label1',
'grid_field1',
'grid_field_label2',
'grid_field2',
'simple_grid_field9',
'simple_grid_field6',
'simple_grid_field12',
'simple_grid_field7' ),
'top' => array(  ) ),
'formXtTags' => array( 'above-grid' => array( 'details_found',
'recsPerPage',
'print_friendly' ),
'below-grid' => array( 'pagination' ),
'top' => array(  ) ),
'itemForms' => array( 'logo1' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'print_panel' => 'above-grid',
'pagination' => 'below-grid',
'grid_checkbox' => 'grid',
'grid_edit' => 'grid',
'grid_view' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field2' => 'grid',
'grid_field_label' => 'grid',
'grid_field' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field5' => 'grid',
'grid_field_label1' => 'grid',
'grid_field1' => 'grid',
'grid_field_label2' => 'grid',
'grid_field2' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field7' => 'grid' ),
'itemLocations' => array( 'grid_checkbox' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'grid_edit' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'grid_view' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_label' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_field_label' => array( 'location' => 'grid',
'cellId' => 'cell_label1' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_label2' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'cell_label3' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_label6' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_label7' ),
'grid_field_label1' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'grid_field_label2' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ) ),
'itemVisiblity' => array( 'expand_button' => 5,
'menu' => 3,
'search_panel' => 5,
'collapse_button' => 5,
'simple_search' => 3,
'list_options' => 3,
'loginform_login' => 3,
'username_button' => 3,
'print_panel' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'breadcrumb' => array( 'breadcrumb' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'list_options' => array( 'list_options' ),
'grid_field' => array( 'simple_grid_field11',
'simple_grid_field10',
'simple_grid_field7',
'simple_grid_field6',
'simple_grid_field5',
'simple_grid_field2',
'grid_field',
'grid_field1',
'grid_field2' ),
'grid_field_label' => array( 'simple_grid_field14',
'simple_grid_field13',
'simple_grid_field12',
'simple_grid_field9',
'simple_grid_field8',
'simple_grid_field',
'grid_field_label',
'grid_field_label1',
'grid_field_label2' ),
'-' => array( '-3',
'-',
'-1',
'-2' ),
'advsearch_link' => array( 'advsearch_link' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'collapse_button' => array( 'collapse_button' ),
'grid_checkbox' => array( 'grid_checkbox' ),
'grid_checkbox_head' => array( 'grid_checkbox_head' ),
'logo' => array( 'logo1' ),
'grid_edit' => array( 'grid_edit' ),
'grid_view' => array( 'grid_view' ),
'print_panel' => array( 'print_panel' ),
'print_scope' => array( 'print_scope' ),
'print_button' => array( 'print_button' ),
'print_records' => array( 'print_records' ),
'search_panel' => array( 'search_panel' ),
'search_panel_field' => array( 'search_panel_field',
'search_panel_field1',
'search_panel_field2',
'search_panel_field3',
'search_panel_field4',
'search_panel_field5',
'search_panel_field6',
'search_panel_field7',
'search_panel_field8',
'search_panel_field9',
'search_panel_field10',
'search_panel_field11',
'search_panel_field12',
'search_panel_field13',
'search_panel_field14',
'search_panel_field15',
'search_panel_field16',
'search_panel_field17',
'search_panel_field48',
'search_panel_field47',
'search_panel_field46',
'search_panel_field45',
'search_panel_field44',
'search_panel_field43',
'search_panel_field42',
'search_panel_field41',
'search_panel_field40',
'search_panel_field39',
'search_panel_field38',
'search_panel_field37',
'search_panel_field36',
'search_panel_field35',
'search_panel_field34',
'search_panel_field33',
'search_panel_field32',
'search_panel_field31',
'search_panel_field30',
'search_panel_field29',
'search_panel_field28',
'search_panel_field27',
'search_panel_field26',
'search_panel_field25',
'search_panel_field24',
'search_panel_field23',
'search_panel_field22',
'search_panel_field21',
'search_panel_field20',
'search_panel_field19',
'search_panel_field18',
'search_panel_field49',
'search_panel_field50' ),
'show_search_panel' => array( 'show_search_panel' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'cell_top' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 0 ),
'tags' => array( 'checkbox_column',
'edit_column',
'view_column' ),
'items' => array( 'grid_checkbox',
'grid_edit',
'grid_view' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label6' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'contractor_image_fieldheadercolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label7' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'contractor_image_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label8' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label9' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array( 'contractor_doc_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array( 'contractor_doc_id_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label1' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array( 'dem_profesion_fieldheadercolumn' ),
'items' => array( 'grid_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array( 'dem_profesion_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array( 'contractor_name_fieldheadercolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array( 'contractor_name_fieldcolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array( 'contractor_lname_fieldheadercolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array( 'contractor_lname_fieldcolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array( 'contractor_sup_jerarquico_fieldheadercolumn' ),
'items' => array( 'grid_field_label1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array( 'contractor_sup_jerarquico_fieldcolumn' ),
'items' => array( 'grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 2 ),
'rows' => array( 4 ),
'tags' => array( 'contractor_dependencia_fieldheadercolumn' ),
'items' => array( 'grid_field_label2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 3 ),
'rows' => array( 4 ),
'tags' => array( 'contractor_dependencia_fieldcolumn' ),
'items' => array( 'grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label2' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array( 'contractor_email_fieldheadercolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array( 'contractor_email_fieldcolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label3' => array( 'cols' => array( 2 ),
'rows' => array( 5 ),
'tags' => array( 'contractor_email_mincit_fieldheadercolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 5 ),
'tags' => array( 'contractor_email_mincit_fieldcolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 4,
'height' => 7 ) ) ),
'loginForm' => array( 'loginForm' => 1 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 2,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo1',
'expand_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'collapse_button',
'breadcrumb' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'print_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'columns-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'cell_top',
'colspan' => 4 ) ),
'section' => 'head' ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_label6' ),
array( 'cell' => 'cell_label7' ),
array( 'cell' => 'cell_label8' ),
array( 'cell' => 'cell_label9' ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_label' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_label1' ),
array( 'cell' => 'cell_field1' ) ),
'section' => 'body' ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field13' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field9' ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_label2' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_label3' ),
array( 'cell' => 'cell_field3' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_dpreview',
'colspan' => 4 ) ),
'section' => 'foot' ) ),
'cells' => array( 'cell_top' => array( 'model' => 'cell_top',
'items' => array( 'grid_checkbox',
'grid_edit',
'grid_view' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'cell_dpreview' => array( 'model' => 'cell_dpreview',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'cell_label' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field' ),
'field' => 'contractor_doc_id',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'contractor_doc_id',
'columnName' => 'field' ),
'cell_label1' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label' ),
'field' => 'dem_profesion',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'field' => 'dem_profesion',
'columnName' => 'field' ),
'cell_label2' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field13' ),
'field' => 'contractor_email',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'contractor_email',
'columnName' => 'field' ),
'cell_label3' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field14' ),
'field' => 'contractor_email_mincit',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'contractor_email_mincit',
'columnName' => 'field' ),
'cell_label6' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field8' ),
'field' => 'contractor_image',
'columnName' => 'field' ),
'cell_label7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'contractor_image',
'columnName' => 'field' ),
'cell_label8' => array( 'model' => 'cell_label',
'items' => array(  ) ),
'cell_label9' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field6' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label1' ),
'field' => 'contractor_sup_jerarquico',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'grid_field1' ),
'field' => 'contractor_sup_jerarquico',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label2' ),
'field' => 'contractor_dependencia',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'grid_field2' ),
'field' => 'contractor_dependencia',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field9' ),
'field' => 'contractor_name',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'contractor_name',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field12' ),
'field' => 'contractor_lname',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'contractor_lname',
'columnName' => 'field' ) ),
'deferredItems' => array( 'grid_checkbox_head' ),
'buildType' => 2,
'columnCount' => 2 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'advsearch_link',
'show_search_panel',
'hide_search_panel' ) ),
'simple_grid_field11' => array( 'field' => 'contractor_email_mincit',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field10' => array( 'field' => 'contractor_email',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field14' => array( 'type' => 'grid_field_label',
'field' => 'contractor_email_mincit',
'clickSort' => false ),
'simple_grid_field7' => array( 'field' => 'contractor_lname',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field6' => array( 'field' => 'contractor_name',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field5' => array( 'field' => 'contractor_image',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field13' => array( 'type' => 'grid_field_label',
'field' => 'contractor_email',
'clickSort' => false ),
'simple_grid_field12' => array( 'type' => 'grid_field_label',
'field' => 'contractor_lname',
'clickSort' => false ),
'simple_grid_field2' => array( 'field' => 'contractor_doc_id',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field9' => array( 'type' => 'grid_field_label',
'field' => 'contractor_name',
'clickSort' => false ),
'simple_grid_field8' => array( 'type' => 'grid_field_label',
'field' => 'contractor_image',
'clickSort' => false ),
'-3' => array( 'type' => '-' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'logout_link',
'adminarea_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => true ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'grid_checkbox' => array( 'type' => 'grid_checkbox' ),
'grid_checkbox_head' => array( 'type' => 'grid_checkbox_head' ),
'-' => array( 'type' => '-' ),
'-1' => array( 'type' => '-' ),
'-2' => array( 'type' => '-' ),
'simple_grid_field' => array( 'type' => 'grid_field_label',
'field' => 'contractor_doc_id',
'clickSort' => false ),
'logo1' => array( 'type' => 'logo' ),
'grid_edit' => array( 'type' => 'grid_edit',
'popup' => false,
'icon' => array( 'file' => 'User Edit-02-WF.png' ),
'buttonStyle' => 'primary',
'buttonSize' => 'xtra-small',
'label' => array( 'text' => 'Actualizar datos',
'type' => 0 ) ),
'grid_view' => array( 'type' => 'grid_view',
'popup' => true,
'icon' => array( 'file' => 'User OK-02-WF.png' ),
'buttonStyle' => 'info',
'buttonSize' => 'xtra-small' ),
'print_panel' => array( 'type' => 'print_panel',
'items' => array( 'print_scope',
'print_records',
'print_button' ) ),
'print_scope' => array( 'type' => 'print_scope' ),
'print_button' => array( 'type' => 'print_button' ),
'print_records' => array( 'type' => 'print_records' ),
'grid_field' => array( 'field' => 'dem_profesion',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label' => array( 'type' => 'grid_field_label',
'field' => 'dem_profesion',
'clickSort' => false ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field',
'search_panel_field50',
'search_panel_field49',
'search_panel_field48',
'search_panel_field47',
'search_panel_field46',
'search_panel_field45',
'search_panel_field44',
'search_panel_field43',
'search_panel_field42',
'search_panel_field41',
'search_panel_field40',
'search_panel_field39',
'search_panel_field38',
'search_panel_field37',
'search_panel_field36',
'search_panel_field35',
'search_panel_field34',
'search_panel_field33',
'search_panel_field32',
'search_panel_field31',
'search_panel_field30',
'search_panel_field29',
'search_panel_field28',
'search_panel_field27',
'search_panel_field26',
'search_panel_field25',
'search_panel_field24',
'search_panel_field23',
'search_panel_field22',
'search_panel_field21',
'search_panel_field20',
'search_panel_field19',
'search_panel_field18',
'search_panel_field17',
'search_panel_field16',
'search_panel_field15',
'search_panel_field14',
'search_panel_field13',
'search_panel_field12',
'search_panel_field11',
'search_panel_field10',
'search_panel_field9',
'search_panel_field8',
'search_panel_field7',
'search_panel_field6',
'search_panel_field5',
'search_panel_field4',
'search_panel_field3',
'search_panel_field2',
'search_panel_field1' ) ),
'search_panel_field' => array( 'field' => 'dem_profesion',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'search_panel_field1' => array( 'field' => 'contractor_image',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field2' => array( 'field' => 'contractor_id',
'type' => 'search_panel_field' ),
'search_panel_field3' => array( 'field' => 'contractor_type',
'type' => 'search_panel_field' ),
'search_panel_field4' => array( 'field' => 'contractor_doc_id',
'type' => 'search_panel_field' ),
'search_panel_field5' => array( 'field' => 'contractor_doc_dv',
'type' => 'search_panel_field' ),
'search_panel_field6' => array( 'field' => 'contractor_pwd',
'type' => 'search_panel_field' ),
'search_panel_field7' => array( 'field' => 'contractor_name',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field8' => array( 'field' => 'contractor_lname',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field9' => array( 'field' => 'contractor_nombresfull',
'type' => 'search_panel_field' ),
'search_panel_field10' => array( 'field' => 'enlace_sigep',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field11' => array( 'field' => 'contractor_email',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field12' => array( 'field' => 'contractor_email_mincit',
'type' => 'search_panel_field' ),
'search_panel_field13' => array( 'field' => 'contractor_address',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field14' => array( 'field' => 'contractor_phone',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field15' => array( 'field' => 'contractor_mobile',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field16' => array( 'field' => 'contractor_city',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field17' => array( 'field' => 'bank_name',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field48' => array( 'field' => 'terms_acepta',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field47' => array( 'field' => 'terms_msj',
'type' => 'search_panel_field' ),
'search_panel_field46' => array( 'field' => 'emergencia',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field45' => array( 'field' => 'dem_discapacidad',
'type' => 'search_panel_field' ),
'search_panel_field44' => array( 'field' => 'dem_educacion',
'type' => 'search_panel_field' ),
'search_panel_field43' => array( 'field' => 'dem_edad',
'type' => 'search_panel_field' ),
'search_panel_field42' => array( 'field' => 'ct_nacionalidad',
'type' => 'search_panel_field' ),
'search_panel_field41' => array( 'field' => 'ct_fecha_nacimiento',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field40' => array( 'field' => 'dem_ocupacion',
'type' => 'search_panel_field' ),
'search_panel_field39' => array( 'field' => 'dem_genero',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field38' => array( 'field' => 'ubica_extension',
'type' => 'search_panel_field' ),
'search_panel_field37' => array( 'field' => 'ubica_dep',
'type' => 'search_panel_field' ),
'search_panel_field36' => array( 'field' => 'contractor_arl',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field35' => array( 'field' => 'contractor_cajacompensacion',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field34' => array( 'field' => 'contractor_fondopensiones',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field33' => array( 'field' => 'contractor_eps',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field32' => array( 'field' => 'contractor_decljur',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field31' => array( 'field' => 'contractor_picmonetaria_file',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field30' => array( 'field' => 'contractor_medicinapre_file',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field29' => array( 'field' => 'contractor_dependientes',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field28' => array( 'field' => 'active',
'type' => 'search_panel_field' ),
'search_panel_field27' => array( 'field' => 'groupid',
'type' => 'search_panel_field' ),
'search_panel_field26' => array( 'field' => 'sys_last_upd',
'type' => 'search_panel_field' ),
'search_panel_field25' => array( 'field' => 'sys_status',
'type' => 'search_panel_field' ),
'search_panel_field24' => array( 'field' => 'sys_level',
'type' => 'search_panel_field' ),
'search_panel_field23' => array( 'field' => 'sys_date',
'type' => 'search_panel_field' ),
'search_panel_field22' => array( 'field' => 'sys_user',
'type' => 'search_panel_field' ),
'search_panel_field21' => array( 'field' => 'sys_update',
'type' => 'search_panel_field' ),
'search_panel_field20' => array( 'field' => 'iva_regimen',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field19' => array( 'field' => 'bank_cta_number',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field18' => array( 'field' => 'bank_cta_type',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'grid_field1' => array( 'field' => 'contractor_sup_jerarquico',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label1' => array( 'type' => 'grid_field_label',
'field' => 'contractor_sup_jerarquico',
'clickSort' => false ),
'search_panel_field49' => array( 'field' => 'contractor_sup_jerarquico',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'grid_field2' => array( 'field' => 'contractor_dependencia',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label2' => array( 'type' => 'grid_field_label',
'field' => 'contractor_dependencia',
'clickSort' => false ),
'search_panel_field50' => array( 'field' => 'contractor_dependencia',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>