<?php
			$optionsArray = array( 'totals' => array( 'inf_id' => array( 'totalsType' => '' ),
'id_cont_fk' => array( 'totalsType' => '' ),
'inf_consecutivo' => array( 'totalsType' => '' ),
'inf_hash' => array( 'totalsType' => '' ),
'inf_estado' => array( 'totalsType' => '' ),
'inf_fechapresenta' => array( 'totalsType' => '' ),
'inf_periodicidad' => array( 'totalsType' => '' ),
'inf_fecharep_i' => array( 'totalsType' => '' ),
'inf_fecharep_f' => array( 'totalsType' => '' ),
'inf_numerocontrato' => array( 'totalsType' => '' ),
'inf_doccontratista' => array( 'totalsType' => '' ),
'inf_nombrecontratista' => array( 'totalsType' => '' ),
'inf_valorcontrato' => array( 'totalsType' => '' ),
'inf_adicionreduc' => array( 'totalsType' => '' ),
'inf_cdp' => array( 'totalsType' => '' ),
'inf_rp' => array( 'totalsType' => '' ),
'inf_rubrocode' => array( 'totalsType' => '' ),
'inf_rubroname' => array( 'totalsType' => '' ),
'inf_objeto' => array( 'totalsType' => '' ),
'inf_fechasuscripcion' => array( 'totalsType' => '' ),
'inf_fechacont_i' => array( 'totalsType' => '' ),
'inf_fechacont_f' => array( 'totalsType' => '' ),
'inf_plazo' => array( 'totalsType' => '' ),
'inf_vigencia' => array( 'totalsType' => '' ),
'inf_modificacionesplazo' => array( 'totalsType' => '' ),
'inf_intersup' => array( 'totalsType' => '' ),
'inf_nombre' => array( 'totalsType' => '' ),
'inf_cargo' => array( 'totalsType' => '' ),
'inf_dependencia' => array( 'totalsType' => '' ),
'inf_poliza' => array( 'totalsType' => '' ),
'inf_avgejecucion' => array( 'totalsType' => '' ),
'inf_actividades' => array( 'totalsType' => '' ),
'inf_declarainconf' => array( 'totalsType' => '' ),
'inf_declarainconf_obs' => array( 'totalsType' => '' ),
'inf_incumplimiento' => array( 'totalsType' => '' ),
'inf_incumplimiento_obs' => array( 'totalsType' => '' ),
'inf_ssparafisfecha' => array( 'totalsType' => '' ),
'inf_ssparafisnplanilla' => array( 'totalsType' => '' ),
'inf_otrosaspectostecnicos' => array( 'totalsType' => '' ),
'inf_recomyobserva' => array( 'totalsType' => '' ),
'sign_date' => array( 'totalsType' => '' ),
'sign_hash' => array( 'totalsType' => '' ),
'sign_file' => array( 'totalsType' => '' ),
'sign_mailnot' => array( 'totalsType' => '' ),
'file_verifica' => array( 'totalsType' => '' ),
'sign_verificacert' => array( 'totalsType' => '' ),
'cert_date' => array( 'totalsType' => '' ),
'cert_file' => array( 'totalsType' => '' ),
'cert_mail' => array( 'totalsType' => '' ),
'cert_compare' => array( 'totalsType' => '' ),
'inf_ultimopago' => array( 'totalsType' => '' ),
'sys_date' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'id_cont_fk',
'inf_consecutivo',
'inf_hash',
'inf_estado',
'inf_fecharep_i',
'inf_fecharep_f' ),
'exportFields' => array( 'id_cont_fk',
'inf_consecutivo',
'inf_hash',
'inf_estado',
'inf_fecharep_i',
'inf_fecharep_f' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id_cont_fk' => array( 'export_field1' ),
'inf_consecutivo' => array( 'export_field2' ),
'inf_hash' => array( 'export_field3' ),
'inf_estado' => array( 'export_field4' ),
'inf_fecharep_i' => array( 'export_field7' ),
'inf_fecharep_f' => array( 'export_field8' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field7',
'export_field8' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field7',
'export_field8' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field7',
'export_field8' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field1' => array( 'field' => 'id_cont_fk',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'inf_consecutivo',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'inf_hash',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'inf_estado',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'inf_fecharep_i',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'inf_fecharep_f',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 4,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>