<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'inf_consecutivo',
'inf_hash',
'inf_fecharep_i',
'inf_fecharep_f',
'inf_numerocontrato',
'inf_anio',
'inf_doccontratista',
'inf_nombrecontratista',
'inf_estado' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'inf_consecutivo' => array( 'import_field2' ),
'inf_hash' => array( 'import_field3' ),
'inf_fecharep_i' => array( 'import_field7' ),
'inf_fecharep_f' => array( 'import_field8' ),
'inf_numerocontrato' => array( 'import_field9' ),
'inf_anio' => array( 'import_field10' ),
'inf_doccontratista' => array( 'import_field12' ),
'inf_nombrecontratista' => array( 'import_field13' ),
'inf_estado' => array( 'import_field' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field2',
'import_field3',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field12',
'import_field13',
'import_field' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field2',
'import_field3',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field12',
'import_field13',
'import_field' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field2',
'import_field3',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field12',
'import_field13',
'import_field' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field2' => array( 'field' => 'inf_consecutivo',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'inf_hash',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'inf_fecharep_i',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'inf_fecharep_f',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'inf_numerocontrato',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'inf_anio',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'inf_doccontratista',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'inf_nombrecontratista',
'type' => 'import_field' ),
'import_field' => array( 'field' => 'inf_estado',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>